name: Spells_V2
main: Spells_V2\Main
api: [3.3.2, 3.3.0, 3.3.1, 3.3.3 , 3.3.4 ,3.3.5 , 4.0.0]
version: 2
author:  L'ombre de Fer
description: Plugin de sort complet ! Concu par L'ombre de Fer.
commands:
  sortinfo:
    usage: "/sortinfo"
    description: "Page d'information sur l'utilisation des sorts"
  sort:
    usage: "/sort"
    description: "Page d'utilisation des sorts"
  job:
    usage: "/job"
    description: "Page de gestion des métiers"