#   ______                            ______ _                     
#  / _____)          _               / _____) |               _    
# | /     _   _  ___| |_  ___  ____ | /     | | _   ____  ___| |_  
# | |    | | | |/___)  _)/ _ \|    \| |     | || \ / _  )/___)  _) 
# | \____| |_| |___ | |_| |_| | | | | \_____| | | ( (/ /|___ | |__ 
#  \______)____(___/ \___)___/|_|_|_|\______)_| |_|\____|___/ \___)
#Ce programme est un plugin privée vous ne pouvez pas le redistribuer ou le modifier sans l'accord de son créateur.
#Ce plugin a été fait initialement par ChimerePatin964 pour le serveur SurvivalsDays

#Si vous mettez sur true cette case cela allumera le plugin au contraire si vous la mettez sur false cela l'empechera de fonctionner
enabled: true

#Commande /id (permett aux joueur de savoir l'id de l'item qu'ils ont dans la main pour pouvoir l'ajouter a un des drawers)
#Mettez false si vous voulez supprimer cette comande (un message d'erreur sera affiché)
ID: true

#Taille du drawer en fonction de l'item 
#0 = incompatible
"1:0": 31
"1:1": 30
"1:2": 32
"1:3": 30
"1:4": 32
"1:5": 30
"1:6": 32
"2:0": 25
"3:0": 23
"3:1": 28
"3:2": 28
"4:0": 30
"5:0": 27
"5:1": 27
"5:2": 27
"5:3": 27
"5:4": 27
"5:5": 27
"6:0": 0
"6:1": 0
"6:2": 0
"6:3": 0
"6:4": 0
"6:5": 0
"7:0": 0
"8:0": 0
"9:0": 0
"10:0": 0
"11:0": 0
"12:0": 24
"12:1": 24
"13:0": 24
"14:0": 39
"15:0": 38
"16:0": 37
"17:0": 31
"17:1": 31
"17:2": 31
"17:3": 31
"18:0": 7
"18:1": 7
"18:2": 7
"18:3": 7
"19:0": 31
"19:1": 31
"21:0": 41
"22:0": 59


