#___________.__              _____       .___  .___            
#\__    ___/|  |__   ____   /  _  \    __| _/__| _/___________ 
#  |    |   |  |  \_/ __ \ /  /_\  \  / __ |/ __ |/ __ \_  __ \
#  |    |   |   Y  \  ___//    |    \/ /_/ / /_/ \  ___/|  | \/
#  |____|   |___|  /\___  >____|__  /\____ \____ |\___  >__|   
#                \/     \/        \/      \/    \/    \/      
        
#Ce programme est un plugin privée vous ne pouvez pas le redistribuer ou le modifier sans l'accord de son créateur.
#Ce plugin a été fait initialement par ChimerePatin964 pour le serveur SurvivalsDays

#Si vous mettez sur true cette case cela allumera le plugin au contraire si vous la mettez sur false cela l'empechera de fonctionner
enabled: true






